import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {/*  bg-[radial-gradient(circle_800px_at_100%_200px,#d5c5ff,transparent)] bg-pink-50 */}
        <div className="inset-0 -z-10 h-full w-full bg-slate-950">
          {children}
        </div>
        <Footer />

      </body>
    </html>
  );
}
